name: Build

on:
  pull_request

jobs:
  build_check:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - name: installing dependencies
        run: npm install
      - name: running unit tests
        run: npm test
      - name: building
        run: npm run build:production
